name:                hw4-Jorres
version:             0.1.0.0
github:              "Jorres/hw4-Jorres"
license:             BSD3
author:              "Jorres"
maintainer:          "jorres.tarasov@gmail.com"
copyright:           "2021 Jorres"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Jorres/hw4-Jorres#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: 
    - random
    - parallel
    - deepseq
    - mtl
    - ListZipper
    - comonad

executables:
  hw4-Jorres-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw4-Jorres

benchmarks:
  hw4-Jorres-bench:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - hw4-Jorres
    - lens
    - mtl
    - containers
    - hspec
    - hspec-discover
    - criterion

tests:
  hw4-Jorres-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - hw4-Jorres
    - lens
    - mtl
    - containers
    - hspec
    - hspec-discover
    - criterion
    - comonad
    - random
